### ISSUE TITLE
No sync

### ISSUE THREAD

**Issue by grand96** [slateprojectteam/slate-core-wallet#1]
Wallet no  sync, 0 connect.

**Comment by rojarsmith** [comment]
Because the few wallet on the net. Don't worry.

Tools -> Open wallet configuration file -> Past and save blow context :

addnode=206.189.170.169
addnode=206.189.69.60

If you don't want addnode, you can just open the wallet and wait 1 hours.

You can wait and mining coins at the same time. Use the command :
setgenerate true 1
